
apiVersion: 1

datasources:
  - name: $PG_DATASOURCE_NAME
    type: postgres
    url: $PG_DATASOURCE_HOST:$PG_DATASOURCE_PORT
    user: $PG_DATASOURCE_GRAFANA_USER
    secureJsonData:
      password: $PG_DATASOURCE_GRAFANA_PASSWORD
    jsonData:
      database: $PG_DATASOURCE_DATABASE
      sslmode: $PG_DATASOURCE_SSL_MODE # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: $PG_DATASOURCE_VERSION # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true